secao-13-projeto-e-commerce/e-commerce/order/urls.py
from django.urls import path
from .views import Pay, SaveOrder, Detail, List

app_name = "order"

urlpatterns = [
    path("pay/<int:pk>", Pay.as_view(), name="pay"),
    path("saveorder/", SaveOrder.as_view(), name="saveorder"),
    path("list/", List.as_view(), name="list"),
    path("detail/<int:pk>", Detail.as_view(), name="detail"),
]

secao-13-projeto-e-commerce/e-commerce/product/urls.py
from django.urls import path
from .views import (
    ProductList,
    ProductDetail,
    ProductAddItem,
    ProductRemoveItem,
    ProductCart,
    ProductCheckout,
    ProductSearch,
)

app_name = "product"

urlpatterns = [
    path("", ProductList.as_view(), name="list"),
    path("<slug>", ProductDetail.as_view(), name="detail"),
    path("additem/", ProductAddItem.as_view(), name="additem"),
    path("removeitem/", ProductRemoveItem.as_view(), name="removeitem"),
    path("cart/", ProductCart.as_view(), name="cart"),
    path("checkout/", ProductCheckout.as_view(), name="checkout"),
    path("search/", ProductSearch.as_view(), name="search"),
]

secao-13-projeto-e-commerce/e-commerce/store/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("", include("product.urls")),
    path("profile/", include("userprofile.urls")),
    path("order/", include("order.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar  # type: ignore

#     urlpatterns = [
#         path("__debug__/", include(debug_toolbar.urls)),
#     ] + urlpatterns

secao-13-projeto-e-commerce/e-commerce/userprofile/urls.py
from django.urls import path
from .views import Create, Login, Logout

app_name = "profile"

urlpatterns = [
    path("", Create.as_view(), name="create"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
]

secao-13-projeto-e-commerce/e-commerce/order/models.py
from django.db import models
from django.contrib.auth.models import User


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qtt_total = models.PositiveIntegerField()
    status = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ("A", "Aprovado"),
            ("C", "Criado"),
            ("R", "Reprovado"),
            ("P", "Pendente"),
            ("E", "Enviado"),
            ("F", "Finalizado"),
        ),
    )

    def __str__(self):
        return f"Pedido N. {self.pk}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.CharField(max_length=255)
    product_id = models.PositiveIntegerField()
    variation = models.CharField(max_length=255)
    variation_id = models.PositiveIntegerField()
    price = models.FloatField()
    price_promotional = models.FloatField(default=0)
    quantity = models.PositiveIntegerField()
    image = models.CharField(max_length=2000)

    def __str__(self):
        return f"Item do {self.order}"

secao-13-projeto-e-commerce/e-commerce/order/views.py
from .models import Order, OrderItem
from product.models import Variation
from django.views import View
from django.views.generic import DetailView, ListView
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from utils import format


class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect("profile:create")

        return super().dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)  # type: ignore
        return qs.filter(user=self.request.user)


class Pay(DispatchLoginRequiredMixin, DetailView):
    template_name = "order/pay.html"
    model = Order
    pk_url_kwarg = "pk"
    context_object_name = "order"


class SaveOrder(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(self.request, "Você precisa fazer login.")
            return redirect("profile:create")

        cart = self.request.session.get("cart")

        if not cart:
            messages.error(self.request, "Carrinho vazio.")
            return redirect("product:list")

        cart_product_id = [v for v in cart]

        db_variations = list(
            Variation.objects.select_related("product").filter(
                id__in=cart_product_id
            )
        )

        for variation in db_variations:
            variation_id = str(variation.pk)
            stock = variation.stock

            qtt_cart = cart[variation_id]["quantity"]
            unitary_price = cart[variation_id]["unitary_price"]
            unitary_promotional_price = cart[variation_id][
                "unitary_promotional_price"
            ]

            error_msg_stock = ""

            if stock < qtt_cart:
                cart[variation_id]["quantity"] = stock
                cart[variation_id]["quantitative_price"] = (
                    stock * unitary_price
                )
                cart[variation_id]["quantitative_promotional_price"] = (
                    stock * unitary_promotional_price
                )

                error_msg_stock = (
                    "Estoque insuficiente, valores corrigidos, "
                    "verifique seu carrinho."
                )

            if error_msg_stock:
                messages.error(self.request, error_msg_stock)
                self.request.session.save()
                return redirect("product:cart")

        qtt_total_cart = format.cart_total_qtt(cart)
        total_cart_value = format.cart_total(cart)

        order = Order(
            user=self.request.user,
            qtt_total=qtt_total_cart,
            total=total_cart_value,
            status="C",
        )

        order.save()

        OrderItem.objects.bulk_create(
            [
                OrderItem(
                    order=order,
                    product=variation["product_name"],
                    product_id=variation["product_id"],
                    variation=variation["variation_name"],
                    variation_id=variation["variation_id"],
                    price=variation["quantitative_price"],
                    price_promotional=variation[
                        "quantitative_promotional_price"
                    ],
                    quantity=variation["quantity"],
                    image=variation["image"],
                )
                for variation in cart.values()
            ]
        )

        del self.request.session["cart"]

        return redirect(reverse("order:pay", kwargs={"pk": order.pk}))


class Detail(DispatchLoginRequiredMixin, DetailView):
    model = Order
    context_object_name = "order"
    template_name = "order/detail.html"
    pk_url_kwarg = "pk"


class List(DispatchLoginRequiredMixin, ListView):
    model = Order
    context_object_name = "orders"
    template_name = "order/list.html"
    paginate_by = 2
    ordering = ["-id"]

secao-13-projeto-e-commerce/e-commerce/templates/parcials/_cart.html
{% load filters %}

<div class="table-responsive">
    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Produto</th>
            <th>V.</th>
            <th>QTD.</th>
            <th>Total</th>
        </tr>
        
        {% for item in cart.values %}
            <tr>
                <td class="d-none d-lg-block">
                    <img class="cart-img" src="{{ item.image }}">
                </td>
                <td>
                    <a href="{% url "product:detail" item.slug %}">
                        {{ item.product_name }}
                    </a>
                    <a class="ml-3" href="{% url "product:removeitem" %}?vid={{ item.variation_id }}">
                        <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                    </a>
                </td>
                <td>{{ item.variation_name }}</td>
                <td>
                    {{ item.quantity }} x 

                    {% if item.unitary_promotional_price %}
                        {{ item.unitary_promotional_price }}
                    {% else %}
                        {{ item.unitary_price }}
                    {% endif %}
                </td>

                {% if item.quantitative_promotional_price %}
                    <td>{{ item.quantitative_promotional_price | price_format }}</td>
                {% else %}
                    <td>{{ item.quantitative_price | price_format }}</td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
</div>

secao-13-projeto-e-commerce/e-commerce/templates/parcials/_footer.html
{% load static %}

<footer class="container-fluid bg-primary">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1">Feito com Django</span>
                </div>
            </div>
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1">Bruno Ferreira</span>
                </div>
            </div>
        </div>
    </div>
</footer>
<script src="{% static "assets/bootstrap/js/jquery-3.2.1.slim.min.js" %}"></script>
<script src="{% static "assets/bootstrap/js/popper.min.js" %}"></script>
<script src="{% static "assets/bootstrap/js/bootstrap.min.js" %}"></script>
<script defer src="{% static "assets/font-awesome/js/all.js" %}"></script>
<script src="{% static "assets/custom/js/scripts.js" %}"></script>

secao-13-projeto-e-commerce/e-commerce/templates/parcials/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static "assets/bootstrap/css/bootstrap.css" %}">
<link rel="stylesheet" href="{% static "assets/custom/css/style.css" %}">

secao-13-projeto-e-commerce/e-commerce/templates/parcials/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

secao-13-projeto-e-commerce/e-commerce/templates/parcials/_nav.html
{% load filters %}

<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="{% url "product:list" %}">E-commerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown active">
                    <a 
                        class="nav-link dropdown-toggle" 
                        id="navbarDropdown" role="button"
                        data-toggle="dropdown" 
                        aria-haspopup="true" 
                        aria-expanded="false"
                    >
                        Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url "order:list" %}">My Orders</a>
                        <a class="dropdown-item" href="{% url "profile:create" %}">Update Details</a>
                        <a class="dropdown-item" href="{% url "profile:logout" %}">Logout</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url "profile:create" %}">Login</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url "profile:create" %}">Register</a>
                </li>
            {% endif %}

            {% if request.session.cart %}
                <li class="nav-item">
                    <a class="nav-link nav-cart-link active" href="{% url "product:cart" %}">
                        <span class="nav-cart-text mr-1">
                            Carrinho
                        </span>
                        <span class="nav-cart-count mr-1">
                            <strong>{{ request.session.cart | cart_total_qtt }}x</strong>
                        </span>
                        <span class="nav-cart-icon mr-2">
                            <i class="fas fa-shopping-cart"></i>
                        </span>
                    </a>
                </li>
            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url "product:search" %}">
            <input name="search" value="{{ request.GET.search }} "class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

secao-13-projeto-e-commerce/e-commerce/templates/parcials/_order.html
{% load filters %}

<div class="row">
    <div class="col">
        <h3>{{ order }}</h3>

        <div class="row mt-4">
            <div class="col-lg-2 font-weight-bold">Número do pedido:</div>
            <div class="col-lg-4">{{ order.id }}</div>
            <div class="col-lg-2 font-weight-bold">Total a pagar:</div>
            <div class="col-lg-4">{{ order.total | price_format }}</div>

            <div class="col-lg-2 font-weight-bold">QTD. Itens:</div>
            <div class="col-lg-4">{{ order.qtt_total }}</div>
            <div class="col-lg-2 font-weight-bold">Status:</div>
            <div class="col-lg-4">{{ order.get_status_display }}</div>
        </div>

        <div class="row mt-4">
            <div class="col">
                <h3>Produtos</h3>
            </div>
        </div>

        <div class="table-responsive mt-3">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Imagem</th>
                    <th>Produto</th>
                    <th>V.</th>
                    <th>QTD.</th>
                    <th>Total</th>
                </tr>
                
                {% for item in order.orderitem_set.all %}
                    <tr>
                        <td class="d-none d-lg-block">
                            <img class="cart-img" src="{{ item.image }}">
                        </td>
                        <td>{{ item.product }}</td>
                        <td>{{ item.variation }}</td>
                        <td>{{ item.quantity }}</td>

                        {% if item.price_promotional %}
                            <td>{{ item.price_promotional | price_format }}</td>
                        {% else %}
                            <td>{{ item.price | price_format }}</td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

secao-13-projeto-e-commerce/e-commerce/templates/parcials/_pagination.html
{% if is_paginated %}
    <div class="col mt-3 mb-3">
        <div class="row">
            <div class="pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">&laquo;</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                    </li>
                    {% endif %}
        
                    {% for num in page_obj.paginator.page_range %}
        
                    {% if page_obj.number == num %}
                    <li class="page-item active">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                    {% endif %}
        
                    {% endfor %}
        
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endif %}