secao-13-projeto-e-commerce/e-commerce/order/urls.py
from django.urls import path
from .views import Pay, SaveOrder, Detail, List

app_name = "order"

urlpatterns = [
    path("pay/<int:pk>", Pay.as_view(), name="pay"),
    path("saveorder/", SaveOrder.as_view(), name="saveorder"),
    path("list/", List.as_view(), name="list"),
    path("detail/<int:pk>", Detail.as_view(), name="detail"),
]

secao-13-projeto-e-commerce/e-commerce/product/urls.py
from django.urls import path
from .views import (
    ProductList,
    ProductDetail,
    ProductAddItem,
    ProductRemoveItem,
    ProductCart,
    ProductCheckout,
    ProductSearch,
)

app_name = "product"

urlpatterns = [
    path("", ProductList.as_view(), name="list"),
    path("<slug>", ProductDetail.as_view(), name="detail"),
    path("additem/", ProductAddItem.as_view(), name="additem"),
    path("removeitem/", ProductRemoveItem.as_view(), name="removeitem"),
    path("cart/", ProductCart.as_view(), name="cart"),
    path("checkout/", ProductCheckout.as_view(), name="checkout"),
    path("search/", ProductSearch.as_view(), name="search"),
]

secao-13-projeto-e-commerce/e-commerce/store/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("", include("product.urls")),
    path("profile/", include("userprofile.urls")),
    path("order/", include("order.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar  # type: ignore

#     urlpatterns = [
#         path("__debug__/", include(debug_toolbar.urls)),
#     ] + urlpatterns

secao-13-projeto-e-commerce/e-commerce/userprofile/urls.py
from django.urls import path
from .views import Create, Login, Logout

app_name = "profile"

urlpatterns = [
    path("", Create.as_view(), name="create"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
]

secao-13-projeto-e-commerce/e-commerce/product/models.py
import os
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from utils import format
from PIL import Image


class Product(models.Model):
    name = models.CharField(max_length=255)
    description_short = models.TextField(max_length=255)
    description_long = models.TextField()
    image = models.ImageField(
        upload_to="product_images/%Y/%m", null=True, blank=True
    )
    slug = models.SlugField(unique=True, null=True, blank=True)
    price_marketing = models.FloatField(verbose_name="Preço de Venda")
    price_marketing_promotional = models.FloatField(
        default=0, verbose_name="Preço Promocional"
    )
    product_type = models.CharField(
        default="V",
        max_length=1,
        choices=(
            ("V", "Variável"),
            ("S", "Simples"),
        ),
    )

    def get_formated_price(self):
        return format.price_format(self.price_marketing)

    def get_formated_promotional_price(self):
        return format.price_format(self.price_marketing_promotional)

    get_formated_price.short_description = "Preço"
    get_formated_promotional_price.short_description = "Preço Promocional"

    def resize_image(self, image, new_width=800):
        image_full_path = os.path.join(settings.MEDIA_ROOT, image.name)
        image_pil = Image.open(image_full_path)
        original_width, original_height = image_pil.size

        if original_width <= new_width:
            image_pil.close()
            return

        new_heigth = round((new_width * original_height) / original_width)
        new_image = image_pil.resize((new_width, new_heigth), Image.LANCZOS)
        new_image.save(image_full_path, optimize=True, quality=60)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        super().save(*args, **kwargs)

        if self.image:
            self.resize_image(self.image)

    def __str__(self):
        return self.name


class Variation(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.FloatField()
    price_promotional = models.FloatField(default=0)
    stock = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.name or self.product.name

secao-13-projeto-e-commerce/e-commerce/product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.db.models import Q
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Product, Variation
from userprofile.models import UserProfile


class ProductList(ListView):
    model = Product
    template_name = "product/list.html"
    context_object_name = "products"
    paginate_by = 1
    ordering = ["-id"]


class ProductSearch(ProductList):
    # def get_queryset(self):
    #     query = self.request.GET.get("q")

    #     if query:
    #         return Product.objects.filter(name__icontains=query)

    #     return Product.objects.all()

    def get_queryset(self, *args, **kwargs):
        query = (
            self.request.GET.get("search") or self.request.session["search"]
        )
        qs = super().get_queryset(*args, **kwargs)

        if not query:
            return qs

        self.request.session["search"] = query

        qs = qs.filter(
            Q(name__icontains=query)
            | Q(description_short__icontains=query)
            | Q(description_long__icontains=query)
        )

        self.request.session.save()

        return qs


class ProductDetail(DetailView):
    model = Product
    template_name = "product/detail.html"
    context_object_name = "product"
    slug_url_kwarg = "slug"


class ProductAddItem(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            "HTTP_REFERER", reverse("product:list")
        )
        variation_id = self.request.GET.get("vid")

        if not variation_id:
            messages.error(self.request, "O produto não existe.")
            return redirect(http_referer)

        variation = get_object_or_404(Variation, id=variation_id)
        variation_stock = variation.stock
        product = variation.product

        product_id = product.pk
        product_name = product.name
        variation_name = variation.name or ""
        unitary_price = variation.price
        unitary_promotional_price = variation.price_promotional
        quantity = 1
        slug = product.slug
        image = product.image.url

        if variation.stock < 1:
            messages.error(self.request, "Estoque insuficiente.")
            return redirect(http_referer)

        if not self.request.session.get("cart"):
            self.request.session["cart"] = {}
            self.request.session.save()

        cart = self.request.session["cart"]

        if variation_id in cart:
            cart_quantity = cart[variation_id]["quantity"]
            cart_quantity += 1

            if variation_stock < cart_quantity:
                messages.warning(
                    self.request,
                    f"Estoque insuficiente para {cart_quantity}x "
                    f"no produto {product_name}. Adicionamos "
                    f"{variation_stock}x no seu carrinho.",
                )

                cart_quantity = variation_stock

            cart[variation_id]["quantity"] = cart_quantity
            cart[variation_id]["quantitative_price"] = (
                unitary_price * cart_quantity
            )
            cart[variation_id]["quantitative_promotional_price"] = (
                unitary_promotional_price * cart_quantity
            )
        else:
            cart[variation_id] = {
                "product_id": product_id,
                "product_name": product_name,
                "variation_name": variation_name,
                "variation_id": variation_id,
                "unitary_price": unitary_price,
                "unitary_promotional_price": unitary_promotional_price,
                "quantitative_price": unitary_price,
                "quantitative_promotional_price": unitary_promotional_price,
                "quantity": quantity,
                "slug": slug,
                "image": image,
            }

        self.request.session.save()

        messages.success(
            self.request,
            f"Produto {product_name} {variation_name} adicionado ao "
            f"carrinho {cart[variation_id]['quantity']}x.",
        )

        return redirect(http_referer)


class ProductRemoveItem(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            "HTTP_REFERER", reverse("product:list")
        )
        variation_id = self.request.GET.get("vid")

        if not variation_id:
            return redirect(http_referer)

        if not self.request.session.get("cart"):
            return redirect(http_referer)

        if variation_id not in self.request.session["cart"]:
            return redirect(http_referer)

        cart = self.request.session["cart"][variation_id]
        messages.success(
            self.request,
            f"Produto { cart['product_name'] } removido do carrinho.",
        )

        del self.request.session["cart"][variation_id]
        self.request.session.save()

        return redirect(http_referer)


class ProductCart(View):
    def get(self, *args, **kwargs):
        context = {"cart": self.request.session.get("cart", {})}
        return render(self.request, "product/cart.html", context)


class ProductCheckout(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect("profile:create")

        profile = UserProfile.objects.get(user=self.request.user)

        if not profile:
            messages.error(self.request, "Usuário sem perfil.")
            return redirect("profile:create")

        if not self.request.session.get("cart"):
            messages.error(self.request, "Carrinho vazio.")
            return redirect("product:list")

        context = {
            "user": self.request.user,
            "cart": self.request.session["cart"],
        }

        return render(self.request, "product/checkout.html", context)

secao-13-projeto-e-commerce/e-commerce/product/templates/product/cart.html
{% extends "base.html" %}

{% load filters %}

{% block page_title %}Carrinho{% endblock page_title %}

{% block content %}
    {% if cart %}
        <div class="row mt-3">
            <div class="col">
                <h3>Carrinho de compras</h3>
                <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

                {% include "parcials/_cart.html" %}
            </div>
        </div>

        <div class="row">
            <div class="col-lg">
                <p class='lead'>Total no carrinho</p>

                <div class='table-responsive'>
                    <table class="table">
                        <tr>
                            <td class="font-weight-bold">Total</td>
                            <td>{{ cart | cart_total | price_format }}</td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="col-lg mt-auto">

                {% if request.user.is_authenticated %}
                    <a class="btn btn-lg btn-block btn-primary" href="{% url "product:checkout" %}">
                        Comprar
                    </a>
                {% else %}
                    <a class="btn btn-lg btn-block btn-primary" href="{% url "profile:create" %}">
                        Entrar ou Cadastrar
                    </a>
                {% endif %}
            </div>
        </div>
    {% else %}
        <div class="row mt-3">
            <div class="col">
                <h3>Carrinho vazio</h3>
                <p class="lead">Não há produtos no seu carrinho.</p>
            </div>
        </div>
    {% endif %}
{% endblock content %}

secao-13-projeto-e-commerce/e-commerce/product/templates/product/checkout.html
{% extends "base.html" %}
{% load filters %}

{% block page_title %}Resumo da Compra{% endblock page_title %}

{% block content %}
    <div class="row mb-5">
        <div class="col-lg">
            <h2>Resumo da sua compra</h2>

            <p class="lead">Dados do usuário</p>
            <p>Caso precise editar, <a href="{% url "profile:create" %}">clique aqui</a></p>
            <dl class="row">
                <dt class="col-lg-2">Nome:</dt>
                <dd class="col-lg-4">{{ user.first_name }}</dd>
                <dt class="col-lg-2">Sobrenome:</dt>
                <dd class="col-lg-4">{{ user.last_name }}</dd>

                <dt class="col-lg-2">Idade:</dt>
                <dd class="col-lg-4">{{ user.userprofile.age }}</dd>
                <dt class="col-lg-2">Nascimento:</dt>
                <dd class="col-lg-4">{{ user.userprofile.date_of_birth }}</dd>

                <dt class="col-lg-2">CPF:</dt>
                <dd class="col-lg-4">{{ user.userprofile.cpf }}</dd>
                <dt class="col-lg-2">E-mail:</dt>
                <dd class="col-lg-4">{{ user.email }}</dd>
            </dl>

            <p class="lead">Dados de endereço</p>
            <p>Caso precise editar, <a href="{% url "profile:create" %}">clique aqui</a></p>
            <dl class="row">
                <dt class="col-lg-2">Endereço:</dt>
                <dd class="col-lg-4">{{ user.userprofile.address }}</dd>
                <dt class="col-lg-2">Número:</dt>
                <dd class="col-lg-4">{{ user.userprofile.number }}</dd>

                <dt class="col-lg-2">Complemento:</dt>
                <dd class="col-lg-4">{{ user.userprofile.complement }}</dd>
                <dt class="col-lg-2">Bairro:</dt>
                <dd class="col-lg-4">{{ user.userprofile.neighborhood }}</dd>

                <dt class="col-lg-2">Cidade:</dt>
                <dd class="col-lg-4">{{ user.userprofile.city }}</dd>
                <dt class="col-lg-2">Estado:</dt>
                <dd class="col-lg-4">{{ user.userprofile.state }}</dd>

                <dt class="col-lg-2">CEP:</dt>
                <dd class="col-lg-4">{{ user.userprofile.cep }}</dd>
            </dl>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <h3>Resumo do Carrinho</h3>
            <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

            {% include "parcials/_cart.html" %}
        </div>
    </div>

    <div class="row">
        <div class="col-lg">
            <p class='lead'>Total no carrinho</p>

            <div class='table-responsive'>
                <table class="table">
                    <tr>
                        <td class="font-weight-bold">Total</td>
                        <td>{{ cart | cart_total | price_format }}</td>
                    </tr>
                </table>
            </div>
        </div>
        
        <div class="col-lg mt-auto">
            <a class="btn btn-lg btn-block btn-primary" href="{% url "order:saveorder" %}">
                Realizar pedido e pagar
            </a>
        </div>
    </div>

{% endblock content %}

secao-13-projeto-e-commerce/e-commerce/product/templates/product/detail.html
{% extends "base.html" %}
{% load filters %}

{% block page_title %}{{ product.name }}{% endblock page_title %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg">
                    <div class="row no-gutters">
                        <div class="col-lg-12">
                            {% if product.image %}
                                <img class="img-fluid" src="{{ product.image.url }}">
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-lg">
                    <div class="mt-4 mt-lg-0">
                        <h1 class="h2">{{ product.name }}</h1>
                        <p class="lead">{{ product.description_short }}</p>
                        <p class="lead">
                            {% if product.price_marketing_promotional %}
                                <span id="variation-preco-promocional" class="lead product-price">{{ product.price_marketing_promotional | price_format }}</span>
                                <span id="variation-preco" class="lead product-old-price text-muted">{{ product.price_marketing | price_format }}</span>
                            {% else %}
                                <span id="variation-preco" class="lead product-price">{{ product.price_marketing | price_format }}</span>
                            {% endif %}
                        </p>

                        <form action="{% url "product:additem" %}" id="form-add-to-cart">
                            <div class="form-group">
                                <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                                    {% for variation in product.variation_set.all %}
                                        {% if variation.price_promotional %}
                                            <option 
                                                data-preco="{{ variation.price | price_format }}" 
                                                data-preco-promocional="{{ variation.price_promotional | price_format }}" 
                                                value="{{ variation.id }}">
                                                    {% if variation.name %}
                                                        {{ variation.name }}
                                                    {% else %}
                                                        {{ variation }}
                                                    {% endif %}
                                            </option>
                                        {% else %}
                                            <option 
                                                data-preco="{{ variation.price | price_format }}" 
                                                value="{{ variation.id }}">
                                                    {% if variation.name %}
                                                        {{ variation.name }}
                                                    {% else %}
                                                        {{ variation }}
                                                    {% endif %}
                                            </option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="text-left">
                                <button variation="submit" class="btn btn-primary btn-lg btn-block">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                    Adicionar ao carrinho
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <div class="mt-5 mb-5">
                        <h2 class="text-center">{{ product.name }}</h2>
                        {{ product.description_long | linebreaks }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

secao-13-projeto-e-commerce/e-commerce/product/templates/product/list.html
{% extends "base.html" %}
{% load filters %}

{% block page_title %}Produtos{% endblock page_title %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="card-columns">

                {% for product in products %}
                    <div class="card">
                        {% if product.image %}
                            <a href="{% url "product:detail" product.slug %}">
                                <img class="card-img-top" src="{{ product.image.url}}" alt="{{ product.name }}">
                            </a>
                        {% endif %}

                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.description_short }}</p>
                            <div class="container product-price-block text-center">
                                {% if product.price_marketing_promotional %}
                                    <span class="product-price">
                                        {{ product.price_marketing_promotional | price_format }}
                                    </span>
                                    <span class="product-old-price text-muted">
                                        {{ product.price_marketing | price_format }}
                                    </span>
                                {% else %}
                                    <span class="product-price">
                                        {{ product.price_marketing | price_format }}
                                    </span>
                                {% endif %}
                            </div>
                        </div>

                        <div class="card-footer bg-transparent border-top-light-custom text-center">
                            <a href="{% url "product:detail" product.slug %}" class="btn btn-primary btn-sm m-1 btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Comprar
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col">
            {% include "parcials/_pagination.html" %}
        </div>
    </div>
{% endblock content %}